# Remove essa linha aqui
# version: '3.8'

services:
  petfy-api:
    build: .
    container_name: petfy_api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
